### ISSUE TITLE
Encode bytes32 error

### ISSUE THREAD

**Issue by roynalnaruto** [hswick/exw3#36]
I am trying to call a function with the following function signature:
```
get(bytes32)
```

I tried the following:
```
ExW3.Contract.call(:my_contract, :get, ["63cb2f697029ee491b58939796e9013087104b816ce0f51e731e9b03cc50c3b9"])
```

I get the following error:
```
[error] GenServer ContractManager terminating
** (RuntimeError) size mismatch for bytes32: "63cb2f697029ee491b58939796e9013087104b816ce0f51e731e9b03cc50c3b9"
    lib/abi/type_encoder.ex:178: ABI.TypeEncoder.encode_type/2
    lib/abi/type_encoder.ex:199: anonymous fn/2 in ABI.TypeEncoder.encode_type/2
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/abi/type_encoder.ex:191: ABI.TypeEncoder.encode_type/2
    lib/abi/type_encoder.ex:141: ABI.TypeEncoder.do_encode/3
    (exw3) lib/exw3.ex:442: ExW3.encode_method_call/3
    (exw3) lib/exw3.ex:697: ExW3.Contract.eth_call_helper/4
    (exw3) lib/exw3.ex:959: ExW3.Contract.handle_call/3
```

Is the hex string supposed to be encoded in a different format before providing in the arguments?

**Comment by roynalnaruto** [comment]
@hswick I did the following (very shabby):
```elixir
modified =
  "63cb2f697029ee491b58939796e9013087104b816ce0f51e731e9b03cc50c3b9"
  |> String.codepoints()
  |> Enum.chunk_every(2)
  |> Enum.map(fn [a, b] -> a <> b end)
  |> Enum.map(fn a -> String.upcase(a) |> Base.decode16!() end)
  |> Enum.reduce(<<>>, fn a, acc -> acc <> a end)
```

to get `<<99, 203, 47, 105, 112, 41, 238, 73, 27, 88, 147, 151, 150, 233, 1, 48, 135, 16, 75, 129, 108, 224, 245, 30, 115, 30, 155, 3, 204, 80, 195, 185>>`

then I can call the `ExW3.Contract.call(:my_contract, :get, [modified])` to get a response

**Comment by roynalnaruto** [comment]
or simply

```elixir
modified =
  "63cb2f697029ee491b58939796e9013087104b816ce0f51e731e9b03cc50c3b9"
  |> String.upcase()
  |> Base.encode16!()
```

does it too
